In [2]:
import numpy as np

Create a 1D NumPy array with values from 10 to 19.

In [3]:
a = np.arange(10,20)
a


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Create a 3x3 matrix of all True values.

In [7]:
a = np.arange(10,18).reshape(2,2,2)
a

array([[[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]]])

Given arr = np.array([5, 10, 15, 20]), write code to replace the second element with 99

In [10]:
arr = np.array([5, 10, 15, 20])
arr[1] = 22
arr

array([ 5, 22, 15, 20])

Create a 5x5 identity matrix.

In [12]:
a = np.eye(5, dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Generate an array of 7 evenly spaced values between 0 and 1 (inclusive).

In [13]:
a = np.linspace(0,1,7)
a

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

Reverse the following array: np.array([1, 2, 3, 4, 5])

In [15]:
a = np.array([1, 2, 3, 4, 5])
a[::-1]

array([5, 4, 3, 2, 1])

Create a 4x4 matrix with random integers from 0 to 100. Set the first row to all zeros.

In [41]:
a = np.random.randint(1,100, size=(4,4))
print("Original Matrix: \n", a)

a[:1] = 0
print("After update: \n",a)

Original Matrix: 
 [[ 3 92 37 56]
 [79 59 38 94]
 [24 71 17 97]
 [14 15  8 11]]
After update: 
 [[ 0  0  0  0]
 [79 59 38 94]
 [24 71 17 97]
 [14 15  8 11]]


Extract all elements greater than 50 from this array: arr = np.array([10, 65, 80, 30, 55])

In [42]:
arr = np.array([10, 65, 80, 30, 55])
arr[arr>50]

array([65, 80, 55])

Create a 2D array of shape (3, 4) filled with the value 7.

In [50]:
a = np.ones(12, dtype = int)
_2d_arr = a*7
print(_2d_arr.reshape(3,4))

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


Given this array:

python
Copy code
arr = np.array([[1, 2, 3], [4, 5, 6]])
How do you extract the value 5 using indexing?

In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[1][1]

5