In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [4]:
my_list = [[1, 2, 3],[ 4, 5, 6]]
arr = np.array(my_list)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [7]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [9]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [10]:
a = np.zeros(5, dtype = int)
a

array([0, 0, 0, 0, 0])

In [13]:
a = np.zeros((2,3), dtype = int)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [17]:
a = np.ones(5, dtype= int)
a

array([1, 1, 1, 1, 1])

In [19]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
a = np.ones((3,3), dtype = int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
a = np.linspace(1,10,5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [26]:
a = np.linspace(1,10,2)
a

array([ 1., 10.])

In [27]:
a = np.linspace(1,10,5, endpoint = True)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
a = np.linspace(1,10,5, endpoint = False)
a

array([1. , 2.8, 4.6, 6.4, 8.2])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [32]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
import random

In [35]:
a = np.random.rand(5)
a

array([0.19250825, 0.54048401, 0.47139605, 0.9584189 , 0.89066801])

In [38]:
a = np.random.rand(2,3)
a

array([[0.52018372, 0.96745985, 0.47434714],
       [0.45214482, 0.12770039, 0.03296958]])

In [39]:
a = np.random.rand(3,4)
a

array([[0.88900104, 0.30765214, 0.6236694 , 0.32323784],
       [0.83786859, 0.52728543, 0.37049093, 0.5079285 ],
       [0.16403018, 0.62262695, 0.90152192, 0.65425478]])

In [40]:
a = np.random.randn(5)
a

array([ 0.11286388,  0.62952911, -0.50874123, -1.35075603, -0.08964935])

In [41]:
a = np.random.randn(2,3)
a

array([[ 0.01547181, -0.51997454,  0.96653236],
       [-0.05349165,  0.59463211, -1.31644855]])

In [42]:
a = np.random.randint(5)
a

2

In [45]:
a = np.random.randint(0,5)
a

4

In [48]:
a = np.random.randint(0,10,5)
a

array([6, 1, 6, 4, 8])

In [58]:
a = np.arange(6)
b = np.reshape(a, (2,3))
b

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
a

array([0, 1, 2, 3, 4, 5])

In [65]:
a = np.arange(8)
b = np.reshape(a, (2,2,2))
b

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [69]:
a = np.arange(12)
b = np.reshape(a, (2,3,2))
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [90]:
a = np.arange(1,100)
a1 = np.max(a)
a2 = np.min(a)
print(a1)
print(a2)

99
1


In [97]:
a = np.arange(1,10)
np.argmax(a)

8

In [98]:
a = np.arange(1,10)
np.argmin(a)

0

In [99]:
np.shape(a)

(9,)

In [103]:
a=np.random.randn(5,10)
a

array([[ 1.654674  ,  0.40809929, -1.16551381, -0.28467531,  0.72229706,
         2.18930897, -0.40366263, -0.03523536, -1.10478472,  0.9637045 ],
       [-0.18412861, -1.06365079,  0.06999114,  0.58348705,  0.01925224,
         1.20031977,  0.12639959,  0.75080472, -0.24790907, -0.35585182],
       [-0.08829617,  0.08580016, -0.49593481, -0.86352525,  0.59697955,
         0.98589243, -0.88591058,  0.88973507,  1.1466095 , -0.0554101 ],
       [-1.0039858 ,  0.77171028,  0.31717246, -0.14510859,  0.78836163,
         0.21114624, -0.2602281 ,  1.09950368,  1.86855827,  1.77895817],
       [-0.04273525, -0.29688092,  0.34667511, -0.72852086,  1.46739992,
        -1.61017484,  1.61800313,  1.34177718,  0.44828268,  0.06195224]])

In [104]:
np.shape(a)

(5, 10)

In [105]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [108]:
arr[::2]

array([0, 2, 4, 6, 8])

In [109]:
arr[::3]

array([0, 3, 6, 9])

In [110]:
arr[::4]

array([0, 4, 8])

In [111]:
arr[::5]

array([0, 5])

In [113]:
arr[:5]

array([0, 1, 2, 3, 4])

In [114]:
arr[5:]

array([5, 6, 7, 8, 9])

In [115]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [121]:
arr  = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [122]:
arr[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [123]:
arr[:,1]

array([1, 4, 7])

In [125]:
arr[1:,:2]

array([[3, 4],
       [6, 7]])

In [126]:
arr[1:,1:]

array([[4, 5],
       [7, 8]])

In [127]:
arr  = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [128]:
arr>3

array([False, False, False, False,  True,  True,  True,  True,  True])

In [129]:
arr[arr>3]

array([4, 5, 6, 7, 8])

In [130]:
arr  = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [131]:
arr>3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [132]:
arr[arr>3]

array([4, 5, 6, 7, 8])

In [134]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
a+a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [136]:
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [137]:
a*a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [138]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [139]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [140]:
a/a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [143]:
a.max()

10

In [144]:
a.min()

1

In [147]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [148]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [149]:
np.square(a)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [150]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [151]:
np.sum(a)

55

In [152]:
np.max(a)

10

In [153]:
np.min(a)

1

In [154]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])